# Generated by Django 3.2.7 on 2021-09-21 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0004_digitalcolor_unique_digital_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_full', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_three_fourths', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_half', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_one_fourth', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colors.analogcolor')),
            ],
        ),
    ]
