# Generated by Django 3.2.7 on 2021-09-19 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_alter_analogcolor_tinting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('_integer_value', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)])),
            ],
        ),
    ]
