# Generated by Django 3.2.7 on 2021-09-17 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('transparency', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tinting', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tinting / pigmentation level')),
                ('lightfastness', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('glossiness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('series', models.CharField(max_length=200)),
                ('body', models.CharField(choices=[('heavy', 'HEAVY'), ('medium', 'MEDIUM'), ('light', 'LIGHT')], max_length=50)),
                ('image_url', models.URLField(max_length=1000)),
                ('brandname', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
