# Generated by Django 3.2.7 on 2021-09-19 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogcolor',
            name='tinting',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tinting / pigmentation level'),
        ),
    ]
