# Generated by Django 3.2.7 on 2021-09-18 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_auto_20210917_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_gloss',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_matte',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_medium',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_oil',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_thinner',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_water',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='AnalogRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='colors.analogcolor')),
                ('origin_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.analogcolor')),
            ],
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='recipe_colors',
            field=models.ManyToManyField(related_name='_colors_analogcolor_recipe_colors_+', through='colors.AnalogRecipe', to='colors.AnalogColor'),
        ),
    ]
