# Generated by Django 3.2.7 on 2021-09-18 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_auto_20210918_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogcolor',
            name='medium',
            field=models.CharField(choices=[('acrylic', 'ACRYLIC'), ('oil', 'OIL'), ('watercolor', 'WATERCOLOR'), ('gouache', 'GOUACHE'), ('mixed', 'MIXED'), ('dye', 'DYE'), ('pastel', 'PASTEL'), ('colored_pencil', 'COLORED PENCIL'), ('graphite', 'GRAPHITE'), ('charcoal', 'CHARCOAL'), ('liquid_graphite', 'LIQUID GRAPHITE')], default='oil', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analogcolor',
            name='glossiness',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
