# Generated by Django 3.2.7 on 2021-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_digitalcolor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='digitalcolor',
            constraint=models.UniqueConstraint(fields=('_integer_value',), name='unique_digital_color'),
        ),
    ]
