# Generated by Django 3.2.7 on 2021-09-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_auto_20210918_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_gloss',
            new_name='_recipe_gloss',
        ),
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_matte',
            new_name='_recipe_matte',
        ),
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_medium',
            new_name='_recipe_medium',
        ),
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_oil',
            new_name='_recipe_oil',
        ),
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_thinner',
            new_name='_recipe_thinner',
        ),
        migrations.RenameField(
            model_name='analogcolor',
            old_name='recipe_water',
            new_name='_recipe_water',
        ),
        migrations.RemoveField(
            model_name='analogcolor',
            name='recipe_colors',
        ),
        migrations.AddField(
            model_name='analogcolor',
            name='_recipe_colors',
            field=models.ManyToManyField(related_name='_colors_analogcolor__recipe_colors_+', through='colors.AnalogRecipe', to='colors.AnalogColor'),
        ),
    ]
