# Generated by Django 3.2.7 on 2021-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0005_auto_20210918_2010'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analogrecipe',
            constraint=models.UniqueConstraint(fields=('origin_color', 'ingredient'), name='unique_ingredients_for_each_color'),
        ),
    ]
