# Generated by Django 3.2.7 on 2021-09-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0006_analogrecipe_unique_ingredients_for_each_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analogcolor',
            constraint=models.UniqueConstraint(fields=('body', 'brandname', 'glossiness', 'lightfastness', 'medium', 'name', 'series', 'tinting', 'transparency'), name='unique_color'),
        ),
    ]
