# Generated by Django 3.2.7 on 2021-09-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.CharField(choices=[('small_bottle', 'SMALL BOTTLE'), ('medium_bottle', 'MEDIUM BOTTLE'), ('large_bottle', 'LARGE BOTTLE'), ('extra_large_bottle', 'EXTRA LARGE BOTTLE'), ('small_jar', 'SMALL JAR'), ('medium_jar', 'MEDIUM JAR'), ('large_jar', 'LARGE JAR'), ('extra_large_jar', 'EXTRA LARGE JAR'), ('small_tube', 'SMALL TUBE'), ('medium_tube', 'MEDIUM TUBE'), ('large_tube', 'LARGE TUBE'), ('extra_large_tube', 'EXTRA LARGE TUBE'), ('pencil', 'PENCIL'), ('stick', 'STICK'), ('pen', 'PEN'), ('marker', 'MARKER')], default='small_bottle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('color', 'size'), name='unique_inventory_type'),
        ),
    ]
